version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: spring_boot_db
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  springboot-app:
    build: .
    container_name: springboot-app-container
    ports:
      - "8080:8080"
    environment:
      DBMS_CONNECTION: jdbc:mysql://mysql:3306/spring_boot_db
      DBMS_DRIVER: com.mysql.cj.jdbc.Driver
      DBMS_USERNAME: root
      DBMS_PASSWORD: 123456
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:

volumes:
  mysql-data:

