#url,username,password (config enviroment variable), if enviroment variable not working (use default value)
spring:
  application:
    name: demo
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/spring-boot-mysql}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  servlet:
    context-path: /identity

jwt:
  signerKey: vDIYvoYyFIq7HgU6fBg5FyLgqQJXJ/8qfaBqp7YZtnr6cISc3vdEg+dWTjWp47i5
  valid-duration: 60
  refreshable-duration: 120